sudo: false
language: node_js
node_js:
  - 'stable'
  - '10'
  - '8'
  - '6'

script:
  - npm run test && npm run build
after_script:
  - ls -lh docs/bundle
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    node: 'stable'
  local_dir: docs
